[server]
hostname = "localhost"
node_ip = "127.0.1.1"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"
offset=1

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[user_store]
type = "read_write_ldap_unique_id"
connection_url = "ldap://localhost:${Ports.EmbeddedLDAP.LDAPServerPort}"
connection_name = "uid=admin,ou=system"
connection_password = "admin"
base_dn = "dc=wso2,dc=org"      #refers the base dn on which the user and group search bases will be generated

[database.identity_db]
type = "postgre"
url = "jdbc:postgresql://postgres:5432/postgres?currentSchema=wso2identity_db"
username = "postgres"
password = "admin@123"
driver = "org.postgresql.Driver"

[database.shared_db]
type = "postgre"
url = "jdbc:postgresql://postgres:5432/postgres?currentSchema=wso2shared_db"
username = "postgres"
password = "admin@123"
driver = "org.postgresql.Driver"

[keystore.primary]
file_name = "wso2carbon.jks"
password = "wso2carbon"

# custom identity server as key manager configurations
[[event_listener]]
id = "token_revocation"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "org.wso2.is.notification.ApimOauthEventInterceptor"
order = 1
[event_listener.properties]
notification_endpoint = "https://localhost:9444/internal/data/v1/notify"
username = "${admin.username}"
password = "${admin.password}"
'header.X-WSO2-KEY-MANAGER' = "WSO2IS"

[[resource.access_control]]
context = "(.)/keymanager-operations/user-info/claims(.)"
secure = true
http_method = "GET"
permissions = "/permission/admin/manage/identity/usermgt/list"
scopes = "internal_user_mgt_list"

[[resource.access_control]]
context = "(.*)/keymanager-operations/user-info/claims/generate"
secure = true
http_method = "POST"
permissions = "/permission/admin/manage/identity/usermgt/list"
scopes = "internal_user_mgt_list"

[[resource.access_control]]
context = "(.*)/keymanager-operations/dcr/register"
secure = true
http_method = "POST"
permissions = "/permission/admin/manage/identity/applicationmgt/create"
scopes = "internal_application_mgt_create"

[[resource.access_control]]
context = "(.*)/keymanager-operations/dcr/register(.*)"
secure = true
http_method = "GET"
permissions = "/permission/admin/manage/identity/applicationmgt/view"
scopes = "internal_application_mgt_view"

[[resource.access_control]]
context = "(.*)/keymanager-operations/dcr/register(.*)"
secure = true
http_method = "PUT"
permissions = "/permission/admin/manage/identity/applicationmgt/update"
scopes = "internal_application_mgt_update"

[[resource.access_control]]
context = "(.*)/keymanager-operations/dcr/register(.*)"
secure = true
http_method = "DELETE"
permissions = "/permission/admin/manage/identity/applicationmgt/delete"
scopes = "internal_application_mgt_delete"

[[resource.access_control]]
context="(.*)/identity/metadata/(.*)"
secure="false"
http_method="all"

[[resource.access_control]]
context="(.*)/identity/entitlement/(.*)"
secure="false"
http_method="all"

[[resource.access_control]]
context="(.*)/.well-known(.*)"
secure="false"
http_method="all"

[tenant_context.rewrite]
custom_webapps = ["/keymanager-operations/"]

[config_data]
path = "/_system/is_as_km/config"

[[event_listener]]
id = "mutual_tls_authenticator"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "org.wso2.carbon.identity.oauth2.token.handler.clientauth.mutualtls.MutualTLSClientAuthenticator"
order = "158"
enable = false

[event.default_listener.identity_mgt]
priority= "50"
enable = false
[event.default_listener.governance_identity_mgt]
priority= "95"
enable = true
[event.default_listener.governance_identity_store]
priority= "97"
enable = true

[output_adapter.email]
from_address= "chenriquelemos@gmail.com"
username="chenriquelemos@gmail.com"
password= "6D7A19CCEEE8D2E8E2AF1598BF3B1F68D90B"
hostname= "smtp.elasticemail.com"
port= 2525
enable_start_tls= false
enable_authentication= true

[identity.auth_framework.endpoint]
identity_server_service_url = "https://localhost:9444"

#[identity_mgt.user_onboarding]
#enable_email_verification = true
#verification_email_validity = "1440"
#lock_on_creation=true

[identity_mgt] 
email_sender= "internal"

#[identity_mgt.user_onboarding]
#ask_password_email_validity = "1440"
#password_generator = "org.wso2.carbon.user.mgt.common.DefaultPasswordGenerator"

[identity_mgt.user_onboarding]
ask_password_from_user= true
